AllCops:
  TargetRubyVersion: 2.5.8

Style/Documentation:
  Enabled: false

Style/ClassVars:
  Exclude:
    - 'lib/has_state/configurator.rb'

Gemspec/RequiredRubyVersion:
  Enabled: false

Lint/ConstantDefinitionInBlock:
  Exclude: 
    - 'spec/integration_spec.rb'
    - 'spec/lib/has_state/declarations_spec.rb'
    - 'spec/lib/has_state/inclusions/base_spec.rb'
    - 'spec/lib/has_state/inclusions/class_methods_spec.rb'

Naming/PredicateName:
  Exclude: 
    - 'lib/has_state/inclusions/assign_initial_state.rb'
    - 'lib/has_state/inclusions/class_methods.rb'
    - 'spec/lib/has_state/inclusions/class_methods_spec.rb'

Metrics/BlockLength:
  IgnoredMethods: ['describe']