version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  codebase_healthcheck:
    docker:
      - image: circleci/ruby:3.0
    steps:
      - checkout
      - ruby/bundle-install
      - run:
          command: bundle exec rspec
      - run:
          command: bundle exec rubocop

workflows:
  version: 2
  healthcheck:
    jobs:
      - codebase_healthcheck
